#include "ps2_runtime_parts/runtime_mtvu_and_env.inc"
#include "ps2_runtime_parts/runtime_host_display.inc"
#include "ps2_runtime_parts/runtime_init_and_signals.inc"
#include "ps2_runtime_parts/runtime_guest_heap.inc"
#include "ps2_runtime_parts/runtime_dispatch_and_memory.inc"
